apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $(AZURE_IDENTITY_CLIENT_ID)
    keyvaultName: trading-kv
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
    tenantId: $(AZURE_TENANT_ID)